-- MySQL Script generated by MySQL Workbench
-- 05/12/15 13:29:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dhbwfestivalplanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dhbwfestivalplanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dhbwfestivalplanner` ;
USE `dhbwfestivalplanner` ;

-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`Veranstalter`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`Veranstalter` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NOT NULL,
  `username` VARCHAR(70) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `birth` DATETIME NOT NULL,
  `isEnabled` TINYINT(1) NOT NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`Event`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`Event` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Veranstalter_ID` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `plz` INT NULL DEFAULT -1,
  `city` VARCHAR(100) NULL,
  `date` DATETIME NOT NULL,
  `time` DATETIME NULL,
  `design` INT NOT NULL DEFAULT 1,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Event_Veranstalter_idx` (`Veranstalter_ID` ASC),
  CONSTRAINT `fk_Event_Veranstalter`
    FOREIGN KEY (`Veranstalter_ID`)
    REFERENCES `dhbwfestivalplanner`.`Veranstalter` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`Guests`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`Guests` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Event_ID` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `receivesEmail` TINYINT(1) NOT NULL DEFAULT 0,
  `receivedInvitation` TINYINT(1) NOT NULL DEFAULT 0,
  `eventCode` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Guests_Event1_idx` (`Event_ID` ASC),
  CONSTRAINT `fk_Guests_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `dhbwfestivalplanner`.`Event` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`Messages`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`Messages` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(45) NULL,
  `Veranstalter_ID` INT NOT NULL,
  `Vorgaenger_ID` INT NOT NULL,
  `Messagescol` VARCHAR(45) NULL,
  `Guests_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Messages_Veranstalter1_idx` (`Veranstalter_ID` ASC),
  INDEX `fk_Messages_Messages1_idx` (`Vorgaenger_ID` ASC),
  INDEX `fk_Messages_Guests1_idx` (`Guests_ID` ASC),
  CONSTRAINT `fk_Messages_Veranstalter1`
    FOREIGN KEY (`Veranstalter_ID`)
    REFERENCES `dhbwfestivalplanner`.`Veranstalter` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Messages1`
    FOREIGN KEY (`Vorgaenger_ID`)
    REFERENCES `dhbwfestivalplanner`.`Messages` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Guests1`
    FOREIGN KEY (`Guests_ID`)
    REFERENCES `dhbwfestivalplanner`.`Guests` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`Survey`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`Survey` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NULL,
  `Event_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Survey_Event1_idx` (`Event_ID` ASC),
  CONSTRAINT `fk_Survey_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `dhbwfestivalplanner`.`Event` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`Option`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`Option` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(1000) NULL,
  `Value` INT NULL,
  `Survey_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Option_Survey1_idx` (`Survey_ID` ASC),
  CONSTRAINT `fk_Option_Survey1`
    FOREIGN KEY (`Survey_ID`)
    REFERENCES `dhbwfestivalplanner`.`Survey` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dhbwfestivalplanner`.`budget`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dhbwfestivalplanner`.`budget` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NULL,
  `value` FLOAT NULL,
  `count` INT NULL,
  `Event_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_budget_Event1_idx` (`Event_ID` ASC),
  CONSTRAINT `fk_budget_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `dhbwfestivalplanner`.`Event` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
